// This file is auto-generated by @hey-api/openapi-ts

import { type _JSONValue, defineQueryOptions, type UseMutationOptions } from '@pinia/colada';

import { serializeQueryKeyValue } from '../client';
import { client } from '../client.gen';
import { deleteDeviceDelete, deleteSessionDelete, getAdminIndex, getAuthMe, getClientIndex, getClusterIndex, getDeviceIndex, getLocationIndex, getOrganizationIndex, getSessionIndex, getTestIndex, getZoneIndex, type Options, postAuthConfirmPhone, postAuthLogin, postAuthLogout, postAuthRegister, postAuthResendPhoneCode, postClientRegister, postSessionPause, postSessionResume, postSessionStart } from '../sdk.gen';
import type { DeleteDeviceDeleteData, DeleteSessionDeleteData, GetAdminIndexData, GetAdminIndexResponse, GetAuthMeData, GetAuthMeResponse, GetClientIndexData, GetClientIndexResponse, GetClusterIndexData, GetClusterIndexResponse, GetDeviceIndexData, GetDeviceIndexResponse, GetLocationIndexData, GetLocationIndexResponse, GetOrganizationIndexData, GetOrganizationIndexResponse, GetSessionIndexData, GetSessionIndexResponse, GetTestIndexData, GetZoneIndexData, GetZoneIndexResponse, PostAuthConfirmPhoneData, PostAuthConfirmPhoneResponse, PostAuthLoginData, PostAuthLoginResponse, PostAuthLogoutData, PostAuthRegisterData, PostAuthRegisterResponse, PostAuthResendPhoneCodeData, PostAuthResendPhoneCodeResponse, PostClientRegisterData, PostSessionPauseData, PostSessionPauseResponse, PostSessionResumeData, PostSessionResumeResponse, PostSessionStartData, PostSessionStartResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'path'> & {
        _id: string;
        baseUrl?: _JSONValue;
        body?: _JSONValue;
        query?: _JSONValue;
        tags?: _JSONValue;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (tags) {
        params.tags = tags as unknown as _JSONValue;
    }
    if (options?.body !== undefined) {
        const normalizedBody = serializeQueryKeyValue(options.body);
        if (normalizedBody !== undefined) {
            params.body = normalizedBody;
        }
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query !== undefined) {
        const normalizedQuery = serializeQueryKeyValue(options.query);
        if (normalizedQuery !== undefined) {
            params.query = normalizedQuery;
        }
    }
    return [params];
};

export const getAdminIndexQueryKey = (options?: Options<GetAdminIndexData>) => createQueryKey('getAdminIndex', options);

export const getAdminIndexQuery = defineQueryOptions<Options<GetAdminIndexData>, GetAdminIndexResponse, Error>((options?: Options<GetAdminIndexData>) => ({
    key: getAdminIndexQueryKey(options),
    query: async (context) => {
        const { data } = await getAdminIndex({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const postAuthRegisterMutation = (options?: Partial<Options<PostAuthRegisterData>>): UseMutationOptions<PostAuthRegisterResponse, Options<PostAuthRegisterData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await postAuthRegister({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const postAuthLoginMutation = (options?: Partial<Options<PostAuthLoginData>>): UseMutationOptions<PostAuthLoginResponse, Options<PostAuthLoginData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await postAuthLogin({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const postAuthConfirmPhoneMutation = (options?: Partial<Options<PostAuthConfirmPhoneData>>): UseMutationOptions<PostAuthConfirmPhoneResponse, Options<PostAuthConfirmPhoneData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await postAuthConfirmPhone({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const postAuthResendPhoneCodeMutation = (options?: Partial<Options<PostAuthResendPhoneCodeData>>): UseMutationOptions<PostAuthResendPhoneCodeResponse, Options<PostAuthResendPhoneCodeData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await postAuthResendPhoneCode({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const getAuthMeQueryKey = (options?: Options<GetAuthMeData>) => createQueryKey('getAuthMe', options);

export const getAuthMeQuery = defineQueryOptions<Options<GetAuthMeData>, GetAuthMeResponse, Error>((options?: Options<GetAuthMeData>) => ({
    key: getAuthMeQueryKey(options),
    query: async (context) => {
        const { data } = await getAuthMe({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const postAuthLogoutMutation = (options?: Partial<Options<PostAuthLogoutData>>): UseMutationOptions<unknown, Options<PostAuthLogoutData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await postAuthLogout({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const getClientIndexQueryKey = (options?: Options<GetClientIndexData>) => createQueryKey('getClientIndex', options);

export const getClientIndexQuery = defineQueryOptions<Options<GetClientIndexData>, GetClientIndexResponse, Error>((options?: Options<GetClientIndexData>) => ({
    key: getClientIndexQueryKey(options),
    query: async (context) => {
        const { data } = await getClientIndex({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const postClientRegisterMutation = (options?: Partial<Options<PostClientRegisterData>>): UseMutationOptions<unknown, Options<PostClientRegisterData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await postClientRegister({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const getClusterIndexQueryKey = (options?: Options<GetClusterIndexData>) => createQueryKey('getClusterIndex', options);

export const getClusterIndexQuery = defineQueryOptions<Options<GetClusterIndexData>, GetClusterIndexResponse, Error>((options?: Options<GetClusterIndexData>) => ({
    key: getClusterIndexQueryKey(options),
    query: async (context) => {
        const { data } = await getClusterIndex({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getDeviceIndexQueryKey = (options?: Options<GetDeviceIndexData>) => createQueryKey('getDeviceIndex', options);

export const getDeviceIndexQuery = defineQueryOptions<Options<GetDeviceIndexData>, GetDeviceIndexResponse, Error>((options?: Options<GetDeviceIndexData>) => ({
    key: getDeviceIndexQueryKey(options),
    query: async (context) => {
        const { data } = await getDeviceIndex({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const deleteDeviceDeleteMutation = (options?: Partial<Options<DeleteDeviceDeleteData>>): UseMutationOptions<unknown, Options<DeleteDeviceDeleteData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await deleteDeviceDelete({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const getLocationIndexQueryKey = (options?: Options<GetLocationIndexData>) => createQueryKey('getLocationIndex', options);

export const getLocationIndexQuery = defineQueryOptions<Options<GetLocationIndexData>, GetLocationIndexResponse, Error>((options?: Options<GetLocationIndexData>) => ({
    key: getLocationIndexQueryKey(options),
    query: async (context) => {
        const { data } = await getLocationIndex({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getOrganizationIndexQueryKey = (options?: Options<GetOrganizationIndexData>) => createQueryKey('getOrganizationIndex', options);

export const getOrganizationIndexQuery = defineQueryOptions<Options<GetOrganizationIndexData>, GetOrganizationIndexResponse, Error>((options?: Options<GetOrganizationIndexData>) => ({
    key: getOrganizationIndexQueryKey(options),
    query: async (context) => {
        const { data } = await getOrganizationIndex({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getSessionIndexQueryKey = (options?: Options<GetSessionIndexData>) => createQueryKey('getSessionIndex', options);

export const getSessionIndexQuery = defineQueryOptions<Options<GetSessionIndexData>, GetSessionIndexResponse, Error>((options?: Options<GetSessionIndexData>) => ({
    key: getSessionIndexQueryKey(options),
    query: async (context) => {
        const { data } = await getSessionIndex({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const postSessionStartMutation = (options?: Partial<Options<PostSessionStartData>>): UseMutationOptions<PostSessionStartResponse, Options<PostSessionStartData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await postSessionStart({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const postSessionPauseMutation = (options?: Partial<Options<PostSessionPauseData>>): UseMutationOptions<PostSessionPauseResponse, Options<PostSessionPauseData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await postSessionPause({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const postSessionResumeMutation = (options?: Partial<Options<PostSessionResumeData>>): UseMutationOptions<PostSessionResumeResponse, Options<PostSessionResumeData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await postSessionResume({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const deleteSessionDeleteMutation = (options?: Partial<Options<DeleteSessionDeleteData>>): UseMutationOptions<unknown, Options<DeleteSessionDeleteData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await deleteSessionDelete({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const getTestIndexQueryKey = (options?: Options<GetTestIndexData>) => createQueryKey('getTestIndex', options);

export const getTestIndexQuery = defineQueryOptions<Options<GetTestIndexData>, unknown, Error>((options?: Options<GetTestIndexData>) => ({
    key: getTestIndexQueryKey(options),
    query: async (context) => {
        const { data } = await getTestIndex({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getZoneIndexQueryKey = (options?: Options<GetZoneIndexData>) => createQueryKey('getZoneIndex', options);

export const getZoneIndexQuery = defineQueryOptions<Options<GetZoneIndexData>, GetZoneIndexResponse, Error>((options?: Options<GetZoneIndexData>) => ({
    key: getZoneIndexQueryKey(options),
    query: async (context) => {
        const { data } = await getZoneIndex({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));
