/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthForm: typeof import('./components/forms/AuthForm.vue')['default']
    BirthdayField: typeof import('./components/inputs/BirthdayField.vue')['default']
    CodeConfirmationField: typeof import('./components/inputs/CodeConfirmationField.vue')['default']
    DashboardActiveClientsPanel: typeof import('./components/dashboard/DashboardActiveClientsPanel.vue')['default']
    DashboardAnalyticsPanel: typeof import('./components/dashboard/DashboardAnalyticsPanel.vue')['default']
    DashboardBookingsPanel: typeof import('./components/dashboard/DashboardBookingsPanel.vue')['default']
    DashboardCashMetrics: typeof import('./components/dashboard/DashboardCashMetrics.vue')['default']
    DashboardCategoryMetrics: typeof import('./components/dashboard/DashboardCategoryMetrics.vue')['default']
    DashboardProfileCard: typeof import('./components/dashboard/DashboardProfileCard.vue')['default']
    DashboardSalesPanel: typeof import('./components/dashboard/DashboardSalesPanel.vue')['default']
    DashboardStatusPanel: typeof import('./components/dashboard/DashboardStatusPanel.vue')['default']
    DashboardSummaryMetrics: typeof import('./components/dashboard/DashboardSummaryMetrics.vue')['default']
    DevicesDetailsPanel: typeof import('./components/devices/DevicesDetailsPanel.vue')['default']
    DevicesSectionPanel: typeof import('./components/devices/DevicesSectionPanel.vue')['default']
    EmailField: typeof import('./components/inputs/EmailField.vue')['default']
    PasswordField: typeof import('./components/inputs/PasswordField.vue')['default']
    PhoneConfirmationForm: typeof import('./components/forms/PhoneConfirmationForm.vue')['default']
    PhoneField: typeof import('./components/inputs/PhoneField.vue')['default']
    RegistrationForm: typeof import('./components/forms/RegistrationForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SBtn: typeof import('./components/_s/buttons/SBtn.vue')['default']
    SBtnIcon: typeof import('./components/_s/buttons/SBtnIcon.vue')['default']
    SDateInput: typeof import('./components/_s/inputs/SDateInput.vue')['default']
    SIcon: typeof import('./components/_s/icons/SIcon.vue')['default']
    SMaskInput: typeof import('./components/_s/inputs/SMaskInput.vue')['default']
    SPngIcon: typeof import('./components/_s/icons/SPngIcon.vue')['default']
    SSecondaryBtn: typeof import('./components/_s/buttons/SSecondaryBtn.vue')['default']
    SSmartIcon: typeof import('./components/_s/icons/SSmartIcon.vue')['default']
    SSvgIcon: typeof import('./components/_s/icons/SSvgIcon.vue')['default']
    STextField: typeof import('./components/_s/inputs/STextField.vue')['default']
    STooltip: typeof import('./components/_s/STooltip.vue')['default']
    UsernameField: typeof import('./components/inputs/UsernameField.vue')['default']
  }
}
