/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthForm: typeof import('./components/forms/AuthForm.vue')['default']
    BirthdayField: typeof import('./components/inputs/BirthdayField.vue')['default']
    ClientsList: typeof import('./components/clients/ClientsList.vue')['default']
    ClientsToolbar: typeof import('./components/clients/ClientsToolbar.vue')['default']
    CodeConfirmationField: typeof import('./components/inputs/CodeConfirmationField.vue')['default']
    CommentAboutUserField: typeof import('./components/inputs/CommentAboutUserField.vue')['default']
    DashboardActiveClientsPanel: typeof import('./components/dashboard/DashboardActiveClientsPanel.vue')['default']
    DashboardAnalyticsPanel: typeof import('./components/dashboard/DashboardAnalyticsPanel.vue')['default']
    DashboardBookingsPanel: typeof import('./components/dashboard/DashboardBookingsPanel.vue')['default']
    DashboardCashMetrics: typeof import('./components/dashboard/DashboardCashMetrics.vue')['default']
    DashboardCategoryMetrics: typeof import('./components/dashboard/DashboardCategoryMetrics.vue')['default']
    DashboardProfileCard: typeof import('./components/dashboard/DashboardProfileCard.vue')['default']
    DashboardSalesPanel: typeof import('./components/dashboard/DashboardSalesPanel.vue')['default']
    DashboardStatusPanel: typeof import('./components/dashboard/DashboardStatusPanel.vue')['default']
    DashboardSummaryMetrics: typeof import('./components/dashboard/DashboardSummaryMetrics.vue')['default']
    DashboardTableToggle: typeof import('./components/toggles/DashboardTableToggle.vue')['default']
    DepositChangeField: typeof import('./components/inputs/DepositChangeField.vue')['default']
    DepositModal: typeof import('./components/modals/DepositModal.vue')['default']
    DepositPaymentMethodToggle: typeof import('./components/toggles/DepositPaymentMethodToggle.vue')['default']
    DepositQuickSumToggle: typeof import('./components/toggles/DepositQuickSumToggle.vue')['default']
    DepositUpField: typeof import('./components/inputs/DepositUpField.vue')['default']
    DeviceControl: typeof import('./components/control/DeviceControl.vue')['default']
    DevicesDetailsPanel: typeof import('./components/devices/DevicesDetailsPanel.vue')['default']
    DevicesSectionPanel: typeof import('./components/devices/DevicesSectionPanel.vue')['default']
    DevicesToolbar: typeof import('./components/devices/DevicesToolbar.vue')['default']
    DiscountField: typeof import('./components/inputs/DiscountField.vue')['default']
    ElectricityControl: typeof import('./components/control/ElectricityControl.vue')['default']
    EmailField: typeof import('./components/inputs/EmailField.vue')['default']
    NavLink: typeof import('./components/navigation/NavLink.vue')['default']
    NavMenu: typeof import('./components/navigation/NavMenu.vue')['default']
    NavSection: typeof import('./components/navigation/NavSubMenu.vue/index.js')['default']
    NavSubMenu: typeof import('./components/navigation/NavSubMenu.vue')['default']
    NotificationModal: typeof import('./components/modals/NotificationModal.vue')['default']
    PasswordField: typeof import('./components/inputs/PasswordField.vue')['default']
    PenaltyControl: typeof import('./components/control/PenaltyControl.vue')['default']
    PhoneConfirmationForm: typeof import('./components/forms/PhoneConfirmationForm.vue')['default']
    PhoneField: typeof import('./components/inputs/PhoneField.vue')['default']
    PromoField: typeof import('./components/inputs/PromoField.vue')['default']
    RegistrationForm: typeof import('./components/forms/RegistrationForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SBadge: typeof import('./components/_s/badges/SBadge.vue')['default']
    SBtn: typeof import('./components/_s/buttons/SBtn.vue')['default']
    SBtnIcon: typeof import('./components/_s/buttons/SBtnIcon.vue')['default']
    SDashboardPanel: typeof import('./components/_s/SDashboardPanel.vue')['default']
    SDataTable: typeof import('./components/_s/tables/SDataTable.vue')['default']
    SDateInput: typeof import('./components/_s/inputs/SDateInput.vue')['default']
    SFinanceTile: typeof import('./components/_s/tiles/SFinanceTile.vue')['default']
    SIcon: typeof import('./components/_s/icons/SIcon.vue')['default']
    SMaskInput: typeof import('./components/_s/inputs/SMaskInput.vue')['default']
    SMessageField: typeof import('./components/_s/inputs/SMessageField.vue')['default']
    SplitPaymentField: typeof import('./components/inputs/SplitPaymentField.vue')['default']
    SPngIcon: typeof import('./components/_s/icons/SPngIcon.vue')['default']
    SSearchBar: typeof import('./components/_s/inputs/SSearchBar.vue')['default']
    SSecondaryBtn: typeof import('./components/_s/buttons/SSecondaryBtn.vue')['default']
    SSmartIcon: typeof import('./components/_s/icons/SSmartIcon.vue')['default']
    SSvgIcon: typeof import('./components/_s/icons/SSvgIcon.vue')['default']
    SSwitch: typeof import('./components/_s/switches/SSwitch.vue')['default']
    STextField: typeof import('./components/_s/inputs/STextField.vue')['default']
    STooltip: typeof import('./components/_s/STooltip.vue')['default']
    UsernameField: typeof import('./components/inputs/UsernameField.vue')['default']
  }
}
