// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://vozhak-club-central.shintio.space' | (string & {});
};

export type ActiveAdminDto = {
    connectionId?: string;
    adminName?: string;
    locationId?: string;
    locationName?: string;
    connectedAtUtc?: string;
    lastPingAtUtc?: string;
};

export type ActiveClientDto = {
    connectionId?: string;
    clientName?: string;
    fingerprint?: string;
    adminName?: string;
    locationId?: string;
    locationName?: string;
    connectedAtUtc?: string;
    lastPingAtUtc?: string;
    device?: DeviceDto;
};

export type AuthResponse = {
    isAuthenticated?: boolean;
    requiresPhoneConfirmation?: boolean;
    authToken?: string | null;
    user?: AuthenticatedUserResponse;
    phone?: string | null;
    devConfirmationCode?: string | null;
    message?: string;
};

export type AuthenticatedUserResponse = {
    id?: string;
    userName?: string;
    phone?: string;
    email?: string | null;
    birthDate?: string | null;
    isPhoneConfirmed?: boolean;
};

export type ClusterDto = {
    id?: string;
    organizationId?: string;
    name?: string;
    createdAt?: string;
};

export type ClusterDtoPaginationResult = {
    total?: number;
    page?: number;
    pageSize?: number;
    pages?: number;
    items?: Array<ClusterDto>;
};

export type ConfirmPhoneRequest = {
    phone?: string;
    code?: string;
};

export type DeviceDto = {
    id?: string;
    locationId?: string;
    zoneId?: string | null;
    name?: string;
    createdAt?: string;
};

export type DeviceDtoPaginationResult = {
    total?: number;
    page?: number;
    pageSize?: number;
    pages?: number;
    items?: Array<DeviceDto>;
};

export type LocationDto = {
    id?: string;
    clusterId?: string;
    name?: string;
    createdAt?: string;
};

export type LocationDtoPaginationResult = {
    total?: number;
    page?: number;
    pageSize?: number;
    pages?: number;
    items?: Array<LocationDto>;
};

export type LoginRequest = {
    phone?: string;
    password?: string;
};

export type OrganizationDto = {
    id?: string;
    name?: string;
    createdAt?: string;
};

export type OrganizationDtoPaginationResult = {
    total?: number;
    page?: number;
    pageSize?: number;
    pages?: number;
    items?: Array<OrganizationDto>;
};

export type PhoneConfirmationResponse = {
    phone?: string;
    devConfirmationCode?: string | null;
    message?: string;
};

export type RegisterRequest = {
    userName?: string;
    birthDate?: string | null;
    phone?: string;
    password?: string;
    repeatPassword?: string;
    email?: string | null;
};

export type ResendPhoneCodeRequest = {
    phone?: string;
};

export type SessionDto = {
    id?: string;
    deviceId?: string;
    userId?: string | null;
    status?: SessionStatus;
    statusChangedAt?: string;
    duration?: string;
    createdAt?: string;
};

export type SessionDtoPaginationResult = {
    total?: number;
    page?: number;
    pageSize?: number;
    pages?: number;
    items?: Array<SessionDto>;
};

export type SessionStatus = 0 | 1;

export type ZoneDto = {
    id?: string;
    locationId?: string;
    name?: string;
    createdAt?: string;
};

export type ZoneDtoPaginationResult = {
    total?: number;
    page?: number;
    pageSize?: number;
    pages?: number;
    items?: Array<ZoneDto>;
};

export type GetAdminIndexData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/Admin/Index';
};

export type GetAdminIndexResponses = {
    /**
     * OK
     */
    200: Array<ActiveAdminDto>;
};

export type GetAdminIndexResponse = GetAdminIndexResponses[keyof GetAdminIndexResponses];

export type PostAuthRegisterData = {
    body?: RegisterRequest;
    path?: never;
    query?: never;
    url: '/Auth/Register';
};

export type PostAuthRegisterResponses = {
    /**
     * OK
     */
    200: AuthResponse;
};

export type PostAuthRegisterResponse = PostAuthRegisterResponses[keyof PostAuthRegisterResponses];

export type PostAuthLoginData = {
    body?: LoginRequest;
    path?: never;
    query?: never;
    url: '/Auth/Login';
};

export type PostAuthLoginResponses = {
    /**
     * OK
     */
    200: AuthResponse;
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type PostAuthConfirmPhoneData = {
    body?: ConfirmPhoneRequest;
    path?: never;
    query?: never;
    url: '/Auth/ConfirmPhone';
};

export type PostAuthConfirmPhoneResponses = {
    /**
     * OK
     */
    200: AuthResponse;
};

export type PostAuthConfirmPhoneResponse = PostAuthConfirmPhoneResponses[keyof PostAuthConfirmPhoneResponses];

export type PostAuthResendPhoneCodeData = {
    body?: ResendPhoneCodeRequest;
    path?: never;
    query?: never;
    url: '/Auth/ResendPhoneCode';
};

export type PostAuthResendPhoneCodeResponses = {
    /**
     * OK
     */
    200: PhoneConfirmationResponse;
};

export type PostAuthResendPhoneCodeResponse = PostAuthResendPhoneCodeResponses[keyof PostAuthResendPhoneCodeResponses];

export type GetAuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/Auth/Me';
};

export type GetAuthMeResponses = {
    /**
     * OK
     */
    200: AuthenticatedUserResponse;
};

export type GetAuthMeResponse = GetAuthMeResponses[keyof GetAuthMeResponses];

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/Auth/Logout';
};

export type PostAuthLogoutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetClientIndexData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/Client/Index';
};

export type GetClientIndexResponses = {
    /**
     * OK
     */
    200: Array<ActiveClientDto>;
};

export type GetClientIndexResponse = GetClientIndexResponses[keyof GetClientIndexResponses];

export type PostClientRegisterData = {
    body?: never;
    path?: never;
    query?: {
        fingerprint?: string;
        zoneId?: string;
        name?: string;
    };
    url: '/Client/Register';
};

export type PostClientRegisterResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetClusterIndexData = {
    body?: never;
    path?: never;
    query?: {
        organizationId?: string;
        page?: number;
        pageSize?: number;
    };
    url: '/Cluster/Index';
};

export type GetClusterIndexResponses = {
    /**
     * OK
     */
    200: ClusterDtoPaginationResult;
};

export type GetClusterIndexResponse = GetClusterIndexResponses[keyof GetClusterIndexResponses];

export type GetDeviceIndexData = {
    body?: never;
    path?: never;
    query?: {
        locationId?: string;
        zoneId?: string;
        page?: number;
        pageSize?: number;
    };
    url: '/Device/Index';
};

export type GetDeviceIndexResponses = {
    /**
     * OK
     */
    200: DeviceDtoPaginationResult;
};

export type GetDeviceIndexResponse = GetDeviceIndexResponses[keyof GetDeviceIndexResponses];

export type DeleteDeviceDeleteData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
    };
    url: '/Device/Delete';
};

export type DeleteDeviceDeleteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetLocationIndexData = {
    body?: never;
    path?: never;
    query?: {
        clusterId?: string;
        page?: number;
        pageSize?: number;
    };
    url: '/Location/Index';
};

export type GetLocationIndexResponses = {
    /**
     * OK
     */
    200: LocationDtoPaginationResult;
};

export type GetLocationIndexResponse = GetLocationIndexResponses[keyof GetLocationIndexResponses];

export type GetOrganizationIndexData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
    };
    url: '/Organization/Index';
};

export type GetOrganizationIndexResponses = {
    /**
     * OK
     */
    200: OrganizationDtoPaginationResult;
};

export type GetOrganizationIndexResponse = GetOrganizationIndexResponses[keyof GetOrganizationIndexResponses];

export type GetSessionIndexData = {
    body?: never;
    path?: never;
    query?: {
        deviceId?: string;
        userId?: string;
        page?: number;
        pageSize?: number;
    };
    url: '/Session/Index';
};

export type GetSessionIndexResponses = {
    /**
     * OK
     */
    200: SessionDtoPaginationResult;
};

export type GetSessionIndexResponse = GetSessionIndexResponses[keyof GetSessionIndexResponses];

export type PostSessionStartData = {
    body?: never;
    path?: never;
    query?: {
        deviceId?: string;
        duration?: string;
        userId?: string;
    };
    url: '/Session/Start';
};

export type PostSessionStartResponses = {
    /**
     * OK
     */
    200: SessionDto;
};

export type PostSessionStartResponse = PostSessionStartResponses[keyof PostSessionStartResponses];

export type PostSessionPauseData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
    };
    url: '/Session/Pause';
};

export type PostSessionPauseResponses = {
    /**
     * OK
     */
    200: SessionDto;
};

export type PostSessionPauseResponse = PostSessionPauseResponses[keyof PostSessionPauseResponses];

export type PostSessionResumeData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
    };
    url: '/Session/Resume';
};

export type PostSessionResumeResponses = {
    /**
     * OK
     */
    200: SessionDto;
};

export type PostSessionResumeResponse = PostSessionResumeResponses[keyof PostSessionResumeResponses];

export type DeleteSessionDeleteData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
    };
    url: '/Session/Delete';
};

export type DeleteSessionDeleteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetTestIndexData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/Test/Index';
};

export type GetTestIndexResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetZoneIndexData = {
    body?: never;
    path?: never;
    query?: {
        locationId?: string;
        page?: number;
        pageSize?: number;
    };
    url: '/Zone/Index';
};

export type GetZoneIndexResponses = {
    /**
     * OK
     */
    200: ZoneDtoPaginationResult;
};

export type GetZoneIndexResponse = GetZoneIndexResponses[keyof GetZoneIndexResponses];
